"""Record every sentence the app speaks as a short MP3 in one warm voice.

The iPad's built-in speech voice (what speechSynthesis gets in a web app)
sounds robotic, and the natural Siri voices aren't available to web pages.
So instead of synthesising on the device, every phrase is recorded ahead of
time with Kokoro, a free, Apache-licensed neural TTS model that runs
locally — no account, no API key, and nothing is sent anywhere when the
app plays. audio.js plays these clips and falls back to the device voice
for any sentence that has no clip.

Writes:
  audio/voice/<slug>.mp3   one clip per sentence (skips ones already there)
  src/voice-lines.js       the list of recorded slugs, read by audio.js and
                           cache-manifest.js (so the clips work offline)

Setup (once):
  python -m venv venv && venv/bin/pip install kokoro-onnx soundfile
  curl -LO https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0/kokoro-v1.0.int8.onnx
  curl -LO https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0/voices-v1.0.bin
  (ffmpeg must be on PATH)

Run:
  venv/bin/python tools/make_voice.py --model kokoro-v1.0.int8.onnx --voices voices-v1.0.bin
  Add --force to re-record everything (e.g. after changing VOICE or SPEED).
"""
import argparse, json, os, re, subprocess, sys, tempfile

VOICE = "af_heart"   # warm US English
SPEED = 0.9          # a touch slow: toddlers need the gap between words
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "audio", "voice")


def slug(text):
    # Must match voiceSlug() in src/audio.js.
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", required=True)
    ap.add_argument("--voices", required=True)
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    lines = json.loads(subprocess.check_output(["node", os.path.join(ROOT, "tools", "voice_lines.mjs")]))
    os.makedirs(OUT, exist_ok=True)

    import soundfile as sf
    from kokoro_onnx import Kokoro
    kokoro = Kokoro(args.model, args.voices)

    slugs = []
    for text in lines:
        s = slug(text)
        slugs.append(s)
        dest = os.path.join(OUT, f"{s}.mp3")
        if os.path.exists(dest) and not args.force:
            continue
        audio, rate = kokoro.create(text, voice=VOICE, speed=SPEED, lang="en-us")
        with tempfile.NamedTemporaryFile(suffix=".wav") as wav:
            sf.write(wav.name, audio, rate)
            # Trim leading silence so a tap answers instantly, keep a short
            # tail, and level every clip to the same loudness.
            subprocess.run([
                "ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-i", wav.name,
                "-af", "silenceremove=start_periods=1:start_threshold=-50dB,"
                       "apad=pad_dur=0.15,loudnorm=I=-16:TP=-1.5:LRA=11",
                "-ar", "24000", "-ac", "1", "-b:a", "48k", dest,
            ], check=True)
        print(f"recorded  {text}", file=sys.stderr)

    # Drop clips for sentences the app no longer says.
    keep = {f"{s}.mp3" for s in slugs}
    for f in os.listdir(OUT):
        if f.endswith(".mp3") and f not in keep:
            os.remove(os.path.join(OUT, f))
            print(f"removed   {f}", file=sys.stderr)

    with open(os.path.join(ROOT, "src", "voice-lines.js"), "w") as fh:
        fh.write("/* Generated by tools/make_voice.py — do not edit by hand.\n"
                 "   Slugs of every sentence with a recorded clip in audio/voice/. */\n\n")
        fh.write("export const VOICE_LINES = [\n")
        for s in sorted(set(slugs)):
            fh.write(f"  '{s}',\n")
        fh.write("];\n")
    print(f"{len(set(slugs))} clips in audio/voice/", file=sys.stderr)


if __name__ == "__main__":
    main()
